name: format

on:
  push:
  pull_request:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Format Code
        run: gofmt -s -w .
      - name: If Changes, Fail
        run: git diff --exit-code
  gomod:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Tidy go mod
        run: go mod tidy
      - name: If Changes, Fail
        run: git diff --exit-code
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Check
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check
