# SOURCED FROM: https://github.com/Matt-Gleich/Matt-Gleich/blob/master/standard_documents/workflows/fsync.yml
name: fsync

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *' # Run every 30 minutes

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: gh_fsync
        uses: Matt-Gleich/gh_fsync@master
